export const INTERFACE_TYPE = {
  UserRepository: Symbol.for("UserRepository"),
  UserRegisterInteractor: Symbol.for("UserRegisterInteractor"),
  AuthController: Symbol.for("AuthController"),
  BcryptEngine: Symbol.for("BcryptEngine"),
  TokenManager: Symbol.for("TokenManager"),
  PasswordManager: Symbol.for("PasswordManager"),
  UserModel: Symbol.for("UserModel"),
  SendOtpInteractor: Symbol.for("SendOtpInteractor"),
  OtpService: Symbol.for("OtpService"),
  MailService: Symbol.for("MailService"),
  UserSignInInteractor: Symbol.for("UserSignInInteractor"),
  AccessTokenGeneratorInteractor: Symbol.for("AccessTokenGeneratorInteractor"),
  ResendOtpInteractor: Symbol.for("ResendOtpInteractor"),
  ResetPasswordInteractor: Symbol.for("ResetPasswordInteractor"),
  GoogleAuthInteractor: Symbol.for("GoogleAuthInteractor"),
  GoogleService: Symbol.for("GoogleService"),
  GithubAuthInteractor: Symbol.for("GithubAuthInteractor"),
  GithubService: Symbol.for("GithubService"),
};
