export const INTERFACE_TYPE = {
  AuthController: Symbol.for("AuthController"),
  ProfileController: Symbol.for("ProfileController"),
  UserController: Symbol.for("UserController"),
  UserRepository: Symbol.for("UserRepository"),
  UserRegisterInteractor: Symbol.for("UserRegisterInteractor"),
  BcryptEngine: Symbol.for("BcryptEngine"),
  TokenManager: Symbol.for("TokenManager"),
  PasswordManager: Symbol.for("PasswordManager"),
  UserModel: Symbol.for("UserModel"),
  SendOtpInteractor: Symbol.for("SendOtpInteractor"),
  OtpService: Symbol.for("OtpService"),
  MailService: Symbol.for("MailService"),
  UserSignInInteractor: Symbol.for("UserSignInInteractor"),
  AccessTokenGeneratorInteractor: Symbol.for("AccessTokenGeneratorInteractor"),
  ResendOtpInteractor: Symbol.for("ResendOtpInteractor"),
  ResetPasswordInteractor: Symbol.for("ResetPasswordInteractor"),
  GoogleAuthInteractor: Symbol.for("GoogleAuthInteractor"),
  GoogleService: Symbol.for("GoogleService"),
  GithubAuthInteractor: Symbol.for("GithubAuthInteractor"),
  GithubService: Symbol.for("GithubService"),
  GetProfileInteractor: Symbol.for("GetProfileInteractor"),
  UpdateProfileInteractor: Symbol.for("UpdateProfileInteractor"),
  GetBulkUsersInteractor: Symbol.for("GetBulkUsersInteractor"),
  UserProducer: Symbol.for("UserProducer"),
  UserConsumersHandler: Symbol.for("UserConsumersHandler"),
};
